version: "3.9"
services:
  initdb:
    container_name: initdb
    image: hybrid-servers:latest
    # Linuxissa tämä rivi auttaa hostin MySQL-yhteyteen:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: ./hybrid-auth-server/.env
    working_dir: /usr/src/app/hybrid-auth-server # <-- TÄRKEÄ
    command: ["sh", "-lc", "npm run migrate && npm run seed"]
    restart: "no"

  media:
    image: hybrid-servers:latest
    container_name: media
    env_file:
      - ./hybrid-media-api/.env
    command: ["node", "hybrid-media-api/index.js"]
    ports:
      - "3000:3000"
    restart: unless-stopped

  auth:
    image: hybrid-servers:latest
    container_name: auth
    depends_on:
      initdb:
        condition: service_completed_successfully
    env_file:
      - ./hybrid-auth-server/.env
    command: ["node", "hybrid-auth-server/index.js"]
    ports:
      - "3001:3001"
    restart: unless-stopped

  upload:
    image: hybrid-servers:latest
    container_name: upload
    env_file:
      - ./hybrid-upload-server/.env
    command: ["node", "hybrid-upload-server/index.js"]
    ports:
      - "3002:3002"
    restart: unless-stopped
