version: "3.9"
services:
  media:
    image: hybrid-servers:latest
    container_name: media
    env_file:
      - ./hybrid-media-api/.env
    command: ["node", "hybrid-media-api/index.js"]
    ports:
      - "3000:3000"
    restart: unless-stopped

  auth:
    image: hybrid-servers:latest
    container_name: auth
    environment:
      NODE_ENV: development
      DB_HOST: host.docker.internal # katso Linux-ohje alla
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: mediashare
      JWT_SECRET: mysecretkey
      GOOGLE_CLIENT_ID: 633421249784-0ve27n5ta8v9sapimtbifj3r1ccoiipt.apps.googleusercontent.com
    # Linux: lisää seuraava rivi
    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: ["node", "hybrid-auth-server/index.js"]
    ports:
      - "3001:3001"
    restart: unless-stopped

  upload:
    image: hybrid-servers:latest
    container_name: upload
    env_file:
      - ./hybrid-upload-server/.env
    command: ["node", "hybrid-upload-server/index.js"]
    ports:
      - "3002:3002"
    restart: unless-stopped
